window.MAP_CHRONICLE = {
  bounds: { west: -100, south: 14, east: 74, north: 52 },
  world: { w: 3600, h: 1960 },
  sources: {
    land: "assets/maps/world-land-110m.json",
    polities: "assets/maps/chronicle-polities.json"
  },
  empires: {
    "Neo-Babylonian Empire": {
      id: "babylon",
      metal: "gold",
      fill: "rgba(212,175,55,0.46)",
      stroke: "#f3d98a",
      name: "Babylon — Head of Gold",
      beast: "Daniel 7: a lion with eagle’s wings, later given a man’s heart.",
      span: "605–539 B.C.",
      insight: "The first world kingdom of the vision. Glory, learning, and idolatry at their height — and already dated to fall.",
      source: "Daniel 2:38; Babylonian Chronicle. Overlay: Cliopatria / Seshat (approximate).",
      art: "assets/plates/babylon.jpg"
    },
    "Achaemenid Empire": {
      id: "persia",
      metal: "silver",
      fill: "rgba(198,208,220,0.42)",
      stroke: "#e8eef6",
      name: "Medo-Persia — Chest and Arms of Silver",
      beast: "Daniel 7: a bear raised on one side, three ribs in its mouth (Lydia, Babylon, Egypt).",
      span: "539–331 B.C.",
      insight: "Inferior in glory, broader in reach. The ram of Daniel 8. Cyrus is named before he is born.",
      source: "Daniel 2:39; 8:20; Cyrus Cylinder. Overlay: Cliopatria / Seshat (approximate).",
      art: "assets/plates/ram-ulai.jpg"
    },
    "Macedonian Empire": {
      id: "greece",
      metal: "bronze",
      fill: "rgba(183,118,58,0.46)",
      stroke: "#e2b47a",
      name: "Greece — Belly and Thighs of Bronze",
      beast: "Daniel 7: a four-winged, four-headed leopard — Alexander’s speed, then four Diadochi.",
      span: "331–168 B.C.",
      insight: "Bronze is harder than gold. Culture and arms spread faster than any kingdom before it.",
      source: "Daniel 2:39; 8:21. Overlay: Cliopatria / Seshat (approximate).",
      art: "assets/plates/greece.jpg"
    },
    "Antigonid Macedonia": {
      id: "greece",
      metal: "bronze",
      fill: "rgba(183,118,58,0.40)",
      stroke: "#e2b47a",
      name: "Antigonid Macedonia — a bronze remnant",
      beast: "One of the four heads of the leopard after Alexander.",
      span: "After 323 B.C., falling in 168 B.C.",
      insight: "The goat’s great horn is broken. Four take its place. Rome is already at the door.",
      art: "assets/plates/goat-broken.jpg"
    },
    "Seleucid Empire": {
      id: "greece",
      metal: "bronze",
      fill: "rgba(166,104,48,0.38)",
      stroke: "#d4a66a",
      name: "Seleucid East — bronze in Asia",
      beast: "King of the North in the long march of Daniel 11.",
      span: "312–63 B.C.",
      insight: "The eastern bronze kingdom holds the land of the vision until iron arrives from the west.",
      art: "assets/plates/leopard-diadochi.jpg"
    },
    "Roman Republic": {
      id: "rome",
      metal: "iron",
      fill: "rgba(132,140,152,0.44)",
      stroke: "#d5dbe4",
      name: "Rome — Legs of Iron",
      beast: "Daniel 7: a dreadful beast with iron teeth. It crushes and breaks.",
      span: "168 B.C. onward (imperial after Actium)",
      insight: "Iron does not negotiate. The fourth kingdom is the longest and the most terrible.",
      art: "assets/plates/rome.jpg"
    },
    "Eastern Roman Empire": {
      id: "rome",
      metal: "iron",
      fill: "rgba(96,118,148,0.38)",
      stroke: "#c5d0e0",
      name: "Eastern Rome — iron that remains",
      beast: "The same fourth beast, still on the stage when the little horn rises among the ten.",
      span: "After the western collapse of A.D. 476",
      insight: "The legs of iron outlast the western throne. The controversy moves from pagan to papal.",
      art: "assets/maps/stops/theodosian-walls.jpg"
    },
    "Ostrogothic Kingdom": {
      id: "divided",
      metal: "clay",
      fill: "rgba(168,118,84,0.40)",
      stroke: "#e0c09a",
      name: "Ostrogoths — a horn about to be uprooted",
      beast: "One of the three horns plucked up before the little horn (Daniel 7:8, 20, 24).",
      span: "Driven from Rome in A.D. 538",
      insight: "Heruli, Vandals, Ostrogoths. When the third falls, the 1,260 years can begin.",
      art: "assets/study/epochs/chronicle-rome-538.jpg"
    },
    "Papal States": {
      id: "papal",
      metal: "iron-clay",
      fill: "rgba(168,42,48,0.50)",
      stroke: "#f0a8a0",
      name: "Papal Rome — little horn among the ten",
      beast: "Speaks great words, wears out the saints, thinks to change times and law.",
      span: "A.D. 538–1798",
      insight: "Not a fifth metal. The same fourth kingdom in a religious dress, mingled with clay.",
      art: "assets/study/epochs/papal-rome.jpg"
    },
    "French First Republic": {
      id: "wound",
      metal: "wound",
      fill: "rgba(176,48,48,0.28)",
      stroke: "#e89090",
      name: "France — the deadly wound",
      beast: "Revelation 13: the beast that had a wound by a sword and did live.",
      span: "1798: Berthier takes Pius VI",
      insight: "The 1,260 years close on the calendar. The time of the end begins. The wound can heal.",
      art: "assets/maps/stops/paris.jpg"
    },
    "Ottoman Empire": {
      id: "divided",
      metal: "clay",
      fill: "rgba(150,128,92,0.30)",
      stroke: "#d4c4a0",
      name: "Ottoman East — divided clay",
      beast: "The feet of iron and clay: kingdoms that mingle but do not cleave.",
      span: "After the western empire fragments",
      insight: "Europe and the East remain broken. No marriage-union restores the fourth kingdom’s first strength.",
      art: "assets/plates/divided.jpg"
    }
  },
  seas: [
    { name: "Mediterranean", lon: 18.2, lat: 35.0 },
    { name: "Black Sea", lon: 34.2, lat: 43.1 },
    { name: "Red Sea", lon: 38.4, lat: 22.4 },
    { name: "Persian Gulf", lon: 52.0, lat: 26.6 },
    { name: "Caspian", lon: 50.8, lat: 41.8 },
    { name: "Nile", lon: 31.1, lat: 26.8 }
  ],
  cities: [
    { id: "babylon", name: "Babylon", lon: 44.421, lat: 32.542, metal: "gold", pulse: ["y605", "y539"], kicker: "Head of gold", text: "The city of Nebuchadnezzar, Ishtar Gate, and the plain of Dura. Daniel serves here while the gold kingdom is weighed.", scripture: "Daniel 2:38; 4:30", art: "assets/study/babylon-sunset.jpg" },
    { id: "jerusalem", name: "Jerusalem", lon: 35.229, lat: 31.778, metal: "gold", pulse: ["y605", "y457", "y31", "y1844", "y12"], kicker: "The holy city", text: "Taken in 605 B.C., restored under the Persian decrees, and the place where Messiah is cut off in the midst of the week.", scripture: "Daniel 1:1; 9:24–27", art: "assets/maps/stops/jerusalem.jpg" },
    { id: "susa", name: "Susa", lon: 48.258, lat: 32.189, metal: "silver", pulse: ["y457", "y1844"], kicker: "Persian court", text: "A winter capital of the Achaemenids. From this world the decree of Artaxerxes in Ezra 7 goes forth in 457 B.C.", scripture: "Ezra 7:12–26; Daniel 8:2", art: "assets/maps/stops/susa.jpg" },
    { id: "persepolis", name: "Persepolis", lon: 52.891, lat: 29.935, metal: "silver", pulse: ["y539", "y331"], kicker: "Ceremonial heart of Persia", text: "The ram’s house. Alexander takes it after Gaugamela; the silver gives way to bronze.", scripture: "Daniel 8:3–7, 20", art: "assets/study/epochs/persepolis.jpg" },
    { id: "sardis", name: "Sardis", lon: 28.040, lat: 38.488, metal: "silver", pulse: ["y539"], kicker: "Lydia fallen", text: "Croesus falls to Cyrus in 546 B.C. — one of the three ribs in the bear’s mouth.", scripture: "Daniel 7:5", art: "assets/maps/stops/sardis.jpg" },
    { id: "athens", name: "Athens", lon: 23.727, lat: 37.972, metal: "bronze", pulse: ["y331", "y168"], kicker: "Hellenic mind", text: "Not the first capital of Alexander, but the culture that bronze carries farther than any phalanx.", scripture: "Daniel 8:21", art: "assets/maps/stops/athens.jpg" },
    { id: "pella", name: "Pella", lon: 22.521, lat: 40.762, metal: "bronze", pulse: ["y331", "y168"], kicker: "Alexander’s home", text: "The goat comes from the west on the face of the whole earth and touches not the ground.", scripture: "Daniel 8:5–7", art: "assets/maps/stops/pella.jpg" },
    { id: "alexandria", name: "Alexandria", lon: 29.919, lat: 31.200, metal: "bronze", pulse: ["y331", "y12"], kicker: "Hellenistic Egypt", text: "Founded in the wake of the bronze conquest. Later the King of the South in Daniel 11.", scripture: "Daniel 11:5", art: "assets/maps/stops/alexandria.jpg" },
    { id: "rome", name: "Rome", lon: 12.492, lat: 41.890, metal: "iron", pulse: ["y168", "y31", "y538", "y1798"], kicker: "The iron city", text: "Pagan, then papal. The fourth kingdom’s throne, the little horn’s seat, and the place of the 1798 wound.", scripture: "Daniel 2:40; 7:23–25", art: "assets/maps/stops/rome.jpg" },
    { id: "constantinople", name: "Constantinople", lon: 28.978, lat: 41.009, metal: "iron", pulse: ["y538"], kicker: "Eastern iron", text: "The surviving eastern throne while the west is divided among the ten.", scripture: "Daniel 2:41; 7:24", art: "assets/maps/stops/constantinople.jpg" },
    { id: "carthage", name: "Carthage", lon: 10.323, lat: 36.853, metal: "iron", pulse: ["y168"], kicker: "A western rib of iron", text: "Rome’s rival, broken in the Punic Wars as iron begins to devour the Mediterranean.", scripture: "Daniel 7:7, 23", art: "assets/maps/stops/carthage.jpg" }
  ],
  icons: {
    gold: "assets/maps/icons/metal-gold.jpg",
    silver: "assets/maps/icons/metal-silver.jpg",
    bronze: "assets/maps/icons/metal-bronze.jpg",
    iron: "assets/maps/icons/metal-iron.jpg",
    clay: "assets/maps/icons/metal-clay.jpg",
    "iron-clay": "assets/maps/icons/metal-clay.jpg",
    stone: "assets/maps/icons/metal-stone.jpg",
    wound: "assets/maps/icons/key-wound.jpg",
    city: "assets/maps/icons/key-city.jpg",
    battle: "assets/maps/icons/key-battle.jpg",
    decree: "assets/maps/icons/key-decree.jpg",
    sanctuary: "assets/maps/icons/key-sanctuary.jpg",
    miller: "assets/maps/icons/medal-miller.jpg",
    press: "assets/maps/icons/medal-press.jpg",
    camp: "assets/maps/icons/medal-camp.jpg",
    disappointment: "assets/maps/icons/medal-disappointment.jpg",
    edson: "assets/maps/icons/medal-edson.jpg",
    america: "assets/maps/icons/medal-america.jpg",
    telegraph: "assets/maps/icons/medal-telegraph.jpg"
  },
  events: [
    { id: "siege-jerusalem", name: "Siege of Jerusalem", lon: 35.229, lat: 31.778, yearId: "y605", kind: "battle", kicker: "605 B.C.", text: "Jehoiakim’s third year. Temple vessels go to Marduk. Daniel and the Hebrew youths enter Babylon’s court school.", scripture: "Daniel 1:1–6", art: "assets/study/epochs/jerusalem-siege.jpg" },
    { id: "fall-babylon", name: "Fall of Babylon", lon: 44.421, lat: 32.542, yearId: "y539", kind: "battle", kicker: "539 B.C.", text: "Cyrus lowers the Euphrates. Belshazzar’s feast ends. Numbered, weighed, divided.", scripture: "Daniel 5; Isaiah 45:1", art: "assets/study/epochs/babylon-fall.jpg" },
    { id: "artaxerxes-decree", name: "Decree of Artaxerxes", lon: 48.258, lat: 32.189, yearId: "y457", kind: "decree", kicker: "457 B.C.", text: "Ezra 7 — the complete decree to restore and rebuild. The 70 weeks and the 2,300 days start here.", scripture: "Ezra 7; Daniel 9:24–25", art: "assets/study/epochs/chronicle-artaxerxes-decree.jpg" },
    { id: "gaugamela", name: "Gaugamela", lon: 43.40, lat: 36.36, yearId: "y331", kind: "battle", kicker: "331 B.C.", text: "Alexander breaks Darius III on the plain near Arbela. The ram has no power to stand before the goat.", scripture: "Daniel 8:6–7, 20–21", art: "assets/study/epochs/chronicle-gaugamela-clean.jpg" },
    { id: "pydna", name: "Pydna", lon: 22.346, lat: 40.372, yearId: "y168", kind: "battle", kicker: "168 B.C.", text: "Rome shatters Macedon. Bronze yields to iron. The fourth kingdom has come.", scripture: "Daniel 2:40; 8:9", art: "assets/maps/stops/pydna.jpg" },
    { id: "calvary", name: "Calvary", lon: 35.229, lat: 31.776, yearId: "y31", kind: "sanctuary", kicker: "A.D. 31", text: "Messiah is cut off in the midst of the week. The veil tears. Sacrifice and oblation cease.", scripture: "Daniel 9:26–27", art: "assets/study/epochs/calvary.jpg" },
    { id: "ostrogoths-out", name: "Ostrogoths driven from Rome", lon: 12.492, lat: 41.890, yearId: "y538", kind: "battle", kicker: "A.D. 538", text: "The third horn is uprooted. Justinian’s decree can take effect. The 1,260 years begin.", scripture: "Daniel 7:8, 24–25", art: "assets/maps/stops/ostrogoths.jpg" },
    { id: "berthier", name: "Pius VI taken captive", lon: 12.492, lat: 41.890, yearId: "y1798", kind: "wound", kicker: "A.D. 1798", text: "Berthier enters Rome. The deadly wound. The time of the end opens, and the sealed book is to be understood.", scripture: "Daniel 7:25; 12:4; Revelation 13:3", art: "assets/study/epochs/deadly-wound.jpg" },
    { id: "sanctuary-1844", name: "Sanctuary cleansed", lon: 35.229, lat: 31.778, yearId: "y1844", kind: "sanctuary", kicker: "22 Oct 1844", text: "The 2,300 evenings-mornings end. The antitype is not this hill and not a New England field. The sanctuary put right is the heavenly Most Holy Place. The people who lived the date were in America. The mountain of the stone is the whole earth — the map’s rim, not a capital.", scripture: "Daniel 8:14; 2:35, 44; 7:9–14", art: "assets/study/epochs/sanctuary.jpg" },
    { id: "miller-lowhampton", name: "Miller’s farm", lon: -73.256, lat: 43.549, yearId: "y1844", kind: "miller", kicker: "Low Hampton, N.Y.", text: "William Miller (1782–1849), a Baptist farmer and War of 1812 captain, begins public lectures in 1831 from this Washington County farm. He reads Daniel’s metals as one chain and the 2,300 evenings-mornings as years from the 457 B.C. decree. His printed claim is “about the year 1843,” later stretched through the Jewish year into the spring of 1844. He expects Christ to come to this earth and the earth itself to be the sanctuary cleansed by fire. The date-range is his. The later day — 22 October — is not.", scripture: "Daniel 8:14; 2:44; Numbers 14:34", art: "assets/maps/stops/miller-farm.jpg" },
    { id: "himes-boston", name: "Signs of the Times", lon: -71.059, lat: 42.360, yearId: "y1844", kind: "press", kicker: "Boston · 20 Mar 1840", text: "Joshua V. Himes, a Boston Christian-Connection minister, launches Signs of the Times on 20 March 1840 and later The Midnight Cry in New York. Camp meetings, charts, and a cheap press turn a farmer’s Bible study into a public American awakening. By 1844 the Second Advent preaching has crossed denominations in the Northeast — Methodists, Baptists, Christians — in the afterglow of the Second Great Awakening. Check the paper. The date is not a whisper.", scripture: "Daniel 12:4; Habakkuk 2:2", art: "assets/maps/stops/himes-boston.jpg" },
    { id: "exeter-seventh-month", name: "Seventh-month cry", lon: -70.948, lat: 42.981, yearId: "y1844", kind: "camp", kicker: "Exeter, N.H. · Aug 1844", text: "At the mid-August 1844 camp meeting in Exeter, New Hampshire, Samuel S. Snow preaches the “true midnight cry.” Leviticus 16 places sanctuary cleansing on the tenth day of the seventh month. Using the Karaite visible-moon calendar, that Day of Atonement in 1844 falls on 22 October. The movement that had said “about 1843” now has a day. This sitting keeps the year on the 2,300-year line even if you dispute the Karaite day. The Exeter sermon is how America heard the day.", scripture: "Daniel 8:14; Leviticus 16:29–30; Matthew 25:6", art: "assets/maps/stops/exeter-camp.jpg" },
    { id: "disappointment-1844", name: "22 October 1844", lon: -73.180, lat: 43.480, yearId: "y1844", kind: "disappointment", kicker: "The Great Disappointment", text: "Christ does not appear in the New England sky. Newspapers mock the Millerites. The date the arithmetic named is not withdrawn; the event they expected is. They had made the earth the sanctuary and the Second Coming the cleansing. Daniel 8:14 does not say “the earth.” It says the sanctuary is nitsdaq — put right. The disappointment is a mistaken event, not a failed number. Ordinary clothes, ordinary farms: the later tale of white “ascension robes” is a hostile cartoon, not the record.", scripture: "Daniel 8:14, 26–27; Hebrews 8:1–2", art: "assets/maps/stops/oct22-1844.jpg" },
    { id: "edson-port-gibson", name: "Edson’s cornfield", lon: -77.053, lat: 42.957, yearId: "y1844", kind: "edson", kicker: "Port Gibson, N.Y. · 23 Oct", text: "The morning after the disappointment, Hiram Edson and friends walk through a cornfield near Port Gibson, New York. The memory of that Advent circle is that the sanctuary to be cleansed is in heaven, not this earth — Christ entering the Most Holy Place, the Day of Atonement antitype, the court of Daniel 7 already sitting. This is not a government gazette. It is the dated account of the people who would not throw the number away with the wrong event.", scripture: "Daniel 8:14; 7:9–14; Hebrews 9:23–24", art: "assets/maps/stops/edson-cornfield.jpg" },
    { id: "washington-nh", name: "Washington, N.H.", lon: -72.097, lat: 43.176, yearId: "y1844", kind: "america", kicker: "A New England meetinghouse", text: "In this small hill town Rachel Oakes Preston, a Seventh Day Baptist, presses Advent believers on the seventh-day Sabbath in 1844. Frederick Wheeler and the Washington congregation become the first Sabbath-keeping Adventist company. The stone kingdom is not an American sect. The point of the pin is narrower: the same year the 2,300 days close, a New England meetinghouse is already arguing which law the little horn thought to change.", scripture: "Daniel 7:25; Exodus 20:8–11", art: "assets/maps/stops/washington-nh.jpg" },
    { id: "morse-telegraph", name: "What hath God wrought", lon: -77.009, lat: 38.890, yearId: "y1844", kind: "telegraph", kicker: "Washington · 24 May 1844", text: "On 24 May 1844 Samuel F. B. Morse sends the first official telegraph message from the U.S. Capitol to Baltimore: “What hath God wrought” (Numbers 23:23). The same year Polk is elected, Texas annexation is forced, and the Methodist church splits north and south over slavery. This pin does not prove Daniel 8:14. It keeps 1844 from floating as a church slogan: the republic is wiring itself, expanding west, and tearing over bondage in the same twelve months the numbered line ends.", scripture: "Numbers 23:23; Daniel 12:4", art: "assets/maps/stops/morse-telegraph.jpg" },
    { id: "michael-stands", name: "Michael stands up", lon: 35.229, lat: 31.778, yearId: "y12", kind: "stone", kicker: "Daniel 12", text: "Intercession ends. A time of trouble. Sleepers awake. Daniel rests, and stands in his lot.", scripture: "Daniel 12:1–2, 13", art: "assets/study/epochs/resurrection-dawn.jpg" },
    { id: "dura-image", name: "Plain of Dura", lon: 44.55, lat: 32.35, yearId: "y605", kind: "decree", kicker: "c. 594 B.C.", text: "Nebuchadnezzar raises an all-gold image sixty cubits by six and commands the empire to bow. The three refuse. The furnace becomes the pattern of forced worship.", scripture: "Daniel 3:1–18", art: "assets/study/statue-nebuchadnezzar.jpg" },
    { id: "watcher-stump", name: "The banded stump", lon: 44.433, lat: 32.555, yearId: "y605", kind: "decree", kicker: "Daniel 4", text: "A Watcher fells the cosmic tree and bands the stump with iron and bronze. Seven times pass until the king knows that Heaven rules.", scripture: "Daniel 4:17, 30–37", art: "assets/study/epochs/babylon-fall.jpg" },
    { id: "lions-den", name: "The lions’ den", lon: 44.410, lat: 32.530, yearId: "y539", kind: "decree", kicker: "Daniel 6", text: "An unchangeable Medo-Persian law forbids prayer except to the king. Daniel opens his windows toward Jerusalem as he did aforetime.", scripture: "Daniel 6:10, 22", art: "assets/study/daniel-lions-den.jpg" },
    { id: "ulai-vision", name: "Vision at the Ulai", lon: 48.270, lat: 32.195, yearId: "y457", kind: "sanctuary", kicker: "Daniel 8", text: "By the Ulai canal Daniel sees the ram and goat, then a horn that takes away the tamid. Unto 2,300 days; then the sanctuary is put right.", scripture: "Daniel 8:2–14", art: "assets/maps/stops/susa.jpg" },
    { id: "hiddekel-theophany", name: "Man in linen by the Tigris", lon: 44.40, lat: 33.30, yearId: "y12", kind: "stone", kicker: "536 B.C. · Daniel 10", text: "The man in linen appears above the Hiddekel. Michael helps against the prince of Persia. The last vision of the book begins.", scripture: "Daniel 10:4–13; 12:1", art: "assets/study/epochs/resurrection-dawn.jpg" }
  ],
  epochs: [
    {
      id: "y605",
      year: -605,
      mapYear: -600,
      label: "605 B.C.",
      title: "The gold head rises",
      kicker: "Siege of Jerusalem",
      metal: "gold",
      beast: "Lion with eagle’s wings",
      scripture: "Daniel 1:1–2; 2:38",
      summary: "Nebuchadnezzar takes Jerusalem. Daniel enters the court of the first kingdom of the dream.",
      insight: "Captivity is not accident. The Lord gave Judah into his hand, and the head of gold is already on the stage.",
      plate: "assets/maps/chronicle-map-605.jpg",
      art: "assets/study/epochs/jerusalem-siege.jpg",
      camera: { lon: 40.8, lat: 32.8, zoom: 2.55 },
      focus: "babylon",
      event: "siege-jerusalem",
      studySheet: 1,
      galleryId: "head",
      polityOpacity: 1,
      stone: 0,
      excludeNames: ["Macedonian Empire"]
    },
    {
      id: "y539",
      year: -539,
      mapYear: -539,
      label: "539 B.C.",
      title: "Numbered, weighed, divided",
      kicker: "Fall of Babylon",
      metal: "silver",
      beast: "Bear raised on one side",
      scripture: "Daniel 5; 2:39",
      summary: "Cyrus takes Babylon in a night. The silver chest inherits the gold.",
      insight: "Isaiah named Cyrus more than a century earlier. The ram of Daniel 8 now stands on the world stage.",
      plate: "assets/maps/chronicle-map-539.jpg",
      art: "assets/study/epochs/babylon-fall.jpg",
      camera: { lon: 46.5, lat: 32.6, zoom: 2.7 },
      focus: "persia",
      event: "fall-babylon",
      studySheet: 5,
      galleryId: "chest",
      polityOpacity: 1,
      stone: 0
    },
    {
      id: "y457",
      year: -457,
      mapYear: -457,
      label: "457 B.C.",
      title: "The decree that starts the clock",
      kicker: "Artaxerxes I, Ezra 7",
      metal: "silver",
      beast: "The ram still standing",
      scripture: "Ezra 7; Daniel 9:24–25",
      summary: "The complete decree to restore Jerusalem. Seventy weeks are cut off from the 2,300 days.",
      insight: "If the cross landed on time, 1844 is on the same line. Prophecy is dated, not fog.",
      plate: "assets/maps/chronicle-map-457.jpg",
      art: "assets/study/epochs/chronicle-artaxerxes-decree.jpg",
      camera: { lon: 44.0, lat: 33.4, zoom: 2.2 },
      focus: "persia",
      event: "artaxerxes-decree",
      studySheet: 9,
      galleryId: "chest",
      polityOpacity: 1,
      stone: 0
    },
    {
      id: "y331",
      year: -331,
      mapYear: -331,
      label: "331 B.C.",
      title: "The goat from the west",
      kicker: "Gaugamela",
      metal: "bronze",
      beast: "Leopard with four wings",
      scripture: "Daniel 8:5–7, 21",
      summary: "Alexander breaks Persia on the plain of Gaugamela. Bronze succeeds silver.",
      insight: "The great horn is still whole. It will break, and four will stand up for it.",
      plate: "assets/maps/chronicle-map-331.jpg",
      art: "assets/study/epochs/chronicle-gaugamela-clean.jpg",
      camera: { lon: 38.5, lat: 34.5, zoom: 2.15 },
      focus: "greece",
      event: "gaugamela",
      studySheet: 2,
      galleryId: "thighs",
      polityOpacity: 1,
      stone: 0
    },
    {
      id: "y168",
      year: -168,
      mapYear: -168,
      label: "168 B.C.",
      title: "Iron comes from the west",
      kicker: "Pydna — Rome over Macedon",
      metal: "iron",
      beast: "The fourth beast, dreadful and terrible",
      scripture: "Daniel 2:40; 7:7",
      summary: "Rome shatters the last Macedonian king. The fourth kingdom has come.",
      insight: "The little horn of Daniel 8 will wax great toward the pleasant land from this western iron, not from a merely local Greek tyrant.",
      plate: "assets/maps/chronicle-map-168.jpg",
      art: "assets/study/epochs/chronicle-rome-168.jpg",
      camera: { lon: 20.5, lat: 39.0, zoom: 2.35 },
      focus: "rome",
      event: "pydna",
      studySheet: 2,
      galleryId: "legs",
      polityOpacity: 1,
      stone: 0
    },
    {
      id: "y31",
      year: 31,
      mapYear: -168,
      approximateYear: true,
      label: "A.D. 31",
      title: "Messiah cut off",
      kicker: "Midst of the week",
      metal: "iron",
      beast: "Iron still on the throne — but a stone is cut",
      scripture: "Daniel 9:26–27",
      summary: "In the midst of the seventieth week, sacrifice ceases. The earthly courtyard meets its antitype.",
      insight: "The 70th week is Calvary, not a future Antichrist gap. That reading keeps the rest of the line honest.",
      plate: "assets/maps/chronicle-map-168.jpg",
      art: "assets/study/epochs/calvary.jpg",
      camera: { lon: 32.8, lat: 32.6, zoom: 3.1 },
      focus: "rome",
      event: "calvary",
      studySheet: 9,
      galleryId: "stone",
      polityOpacity: 0.55,
      stone: 0.35
    },
    {
      id: "y538",
      year: 538,
      mapYear: 538,
      label: "A.D. 538",
      title: "The little horn among the ten",
      kicker: "Ostrogoths driven from Rome",
      metal: "iron-clay",
      beast: "A horn with eyes and a mouth speaking great things",
      scripture: "Daniel 7:8, 24–25",
      summary: "The third of three horns is uprooted. Papal supremacy of 1,260 years begins.",
      insight: "The controversy is no longer only pagan. A church-state power takes Christ’s daily priesthood and His law into its own hands.",
      plate: "assets/maps/chronicle-map-538.jpg",
      art: "assets/study/epochs/papal-rome.jpg",
      camera: { lon: 16.8, lat: 41.6, zoom: 2.55 },
      focus: "papal",
      event: "ostrogoths-out",
      studySheet: 7,
      galleryId: "years1260",
      polityOpacity: 1,
      stone: 0
    },
    {
      id: "y1798",
      year: 1798,
      mapYear: 1798,
      label: "A.D. 1798",
      title: "The deadly wound",
      kicker: "Berthier takes Pius VI",
      metal: "wound",
      beast: "The beast that had a wound by a sword",
      scripture: "Daniel 7:25; 12:4; Revelation 13:3",
      summary: "Exactly 1,260 years from 538, the political-religious supremacy is broken. The time of the end begins.",
      insight: "The sealed book is to be understood. Historicism does not end here — it warns that the wound can heal.",
      plate: "assets/maps/chronicle-map-1798.jpg",
      art: "assets/study/epochs/deadly-wound.jpg",
      camera: { lon: 14.2, lat: 42.4, zoom: 2.7 },
      focus: "papal",
      event: "berthier",
      studySheet: 7,
      galleryId: "feet",
      polityOpacity: 1,
      stone: 0.12
    },
    {
      id: "y1844",
      year: 1844,
      mapYear: 1798,
      approximateYear: true,
      label: "1844",
      title: "Then shall the sanctuary be cleansed",
      kicker: "22 October 1844 · America",
      metal: "stone",
      beast: "The stone fills the whole earth. It has no capital on this map.",
      scripture: "Daniel 8:14; 2:35, 44; 7:9–14",
      summary: "The 2,300 years end. The people who lived that date were in the American Northeast — Miller’s farm, Himes’s Boston press, Snow at Exeter, the disappointment, Edson’s cornfield. The event they expected was wrong. The sanctuary put right is in heaven.",
      insight: "The stone kingdom is not a shaded province. The map’s borders are the sign: a mountain that fills the whole earth. Judgment is present high-priestly work. The metals do not recover.",
      plate: "assets/maps/chronicle-map-1844-america.jpg",
      art: "assets/maps/stops/oct22-1844.jpg",
      camera: { lon: -73.2, lat: 41.55, zoom: 2.4, tileZoom: 5, useCamera: true },
      focus: "",
      event: "miller-lowhampton",
      studySheet: 8,
      galleryId: "stone",
      polityOpacity: 0.18,
      stone: 0.85
    },
    {
      id: "y12",
      year: 12,
      mapYear: 1798,
      approximateYear: true,
      label: "Dan. 12",
      title: "Michael stands up",
      kicker: "The last scene of the scroll",
      metal: "stone",
      beast: "Not another empire — a standing Prince",
      scripture: "Daniel 12:1–2, 13",
      summary: "Probation closes. Trouble comes. Dust-sleepers awake. Daniel is told to rest, and to stand in his lot.",
      insight: "The map’s last gift is not another border. It is a name in a book, a rest, and a rising.",
      plate: "assets/maps/chronicle-map-daniel12.jpg",
      art: "assets/study/epochs/resurrection-dawn.jpg",
      camera: { lon: 32.0, lat: 34.0, zoom: 1.55 },
      focus: "",
      event: "michael-stands",
      studySheet: 10,
      galleryId: "stone",
      polityOpacity: 0.08,
      stone: 1
    }
  ]
};

window.MAP_CHRONICLE.studyEpochIds = [
  "y605", "y539", "y457", "y31", "y538", "y1798", "y1844", "y12"
];

window.MAP_CHRONICLE.routes = [
  {
    id: "exile",
    yearIds: ["y605"],
    name: "Captives to Babylon",
    stops: [
      { name: "Jerusalem", lat: 31.778, lon: 35.229, art: "assets/study/horizon/y605.jpg" },
      { name: "Babylon", lat: 32.542, lon: 44.421, art: "assets/study/horizon/y539.jpg" }
    ]
  },
  {
    id: "cyrus",
    yearIds: ["y539"],
    name: "Cyrus into Babylon",
    stops: [
      { name: "Susa", lat: 32.189, lon: 48.258, art: "assets/maps/stops/susa.jpg" },
      { name: "Babylon", lat: 32.542, lon: 44.421, art: "assets/study/horizon/y539.jpg" }
    ]
  },
  {
    id: "alexander",
    yearIds: ["y331"],
    name: "The goat from the west",
    stops: [
      { name: "Pella", lat: 40.762, lon: 22.521, art: "assets/maps/stops/pella.jpg" },
      { name: "Gaugamela", lat: 36.36, lon: 43.40, art: "assets/study/epochs/chronicle-gaugamela-clean.jpg" },
      { name: "Persepolis", lat: 29.935, lon: 52.891, art: "assets/study/epochs/persepolis.jpg" }
    ]
  },
  {
    id: "rome-east",
    yearIds: ["y168"],
    name: "Rome over Macedon",
    stops: [
      { name: "Rome", lat: 41.89, lon: 12.492, art: "assets/maps/stops/rome.jpg" },
      { name: "Pydna", lat: 40.372, lon: 22.346, art: "assets/maps/stops/pydna.jpg" }
    ]
  },
  {
    id: "calvary-rome",
    yearIds: ["y31"],
    name: "From Jerusalem to the nations",
    stops: [
      { name: "Jerusalem", lat: 31.778, lon: 35.229, art: "assets/study/horizon/y31.jpg" },
      { name: "Rome", lat: 41.89, lon: 12.492, art: "assets/maps/stops/rome.jpg" }
    ]
  },
  {
    id: "berthier-march",
    yearIds: ["y1798"],
    name: "Berthier takes Rome",
    stops: [
      { name: "Paris", lat: 48.856, lon: 2.352, art: "assets/maps/stops/paris.jpg" },
      { name: "Rome", lat: 41.89, lon: 12.492, art: "assets/study/horizon/y1798.jpg" }
    ]
  },
  {
    id: "america-1844",
    yearIds: ["y1844"],
    name: "The date in America",
    stops: [
      { name: "Low Hampton", lat: 43.549, lon: -73.256, art: "assets/maps/stops/miller-farm.jpg" },
      { name: "Boston", lat: 42.360, lon: -71.059, art: "assets/maps/stops/himes-boston.jpg" },
      { name: "Exeter", lat: 42.981, lon: -70.948, art: "assets/maps/stops/exeter-camp.jpg" },
      { name: "Washington, N.H.", lat: 43.176, lon: -72.097, art: "assets/maps/stops/washington-nh.jpg" },
      { name: "Port Gibson", lat: 42.957, lon: -77.053, art: "assets/maps/stops/edson-cornfield.jpg" }
    ]
  }
];
